# Ejercicios Numpy I

Sirvan estos ejercicios para que fortalezcáis aquellos conceptos más importantes.

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
print(f'La versión de numpy es la {np.__version__}')

La versión de numpy es la 1.19.5


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
true_array = np.ones((3, 3))
true_array = true_array.astype(bool)
true_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [16]:
odd_bol = (my_array % 2 == 1)
my_array[odd_bol]

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [11]:
minus_one_array = my_array.copy()
minus_one_array[my_array % 2 == 1] = -1
minus_one_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [27]:
minus_one_array2 = np.where(my_array % 2 == 1, -1, my_array)
minus_one_array2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [29]:
my_array.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [13]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [4]:
my_array = np.arange(10)
# 1
my_array_10 = my_array * 10
print(my_array_10)
# 2
print(my_array_10[0])
# 3
print(my_array_10[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [21]:
my_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [22]:
secuencia = np.arange(1, 50, 3)
secuencia

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [23]:
secuencia2 = np.arange(4, 1, -0.25)
secuencia2

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen `numpy.png` que encontrarás en la carpeta **img**

In [41]:
import sys, os
import matplotlib.pyplot as plt
from skimage.io import imread

numpy_image = imread("../theory/numpy/img/numpy.png")
numpy_image.shape

(306, 765, 4)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [45]:
array_4x1 = np.array(([1], [2], [3], [4]))
array_4x1 = array_4x1.reshape((2, 2))
array_4x1

array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [48]:
random_matrix = np.random.rand(4, 5, 3)
random_matrix

array([[[0.7504781 , 0.65383965, 0.85679643],
        [0.43729759, 0.39903717, 0.913391  ],
        [0.90430408, 0.13145334, 0.38846882],
        [0.95155769, 0.81970308, 0.70942947],
        [0.45634682, 0.38406145, 0.53317503]],

       [[0.60020457, 0.40952099, 0.44140581],
        [0.80377373, 0.37828492, 0.09085262],
        [0.22938603, 0.81716705, 0.33741223],
        [0.79629951, 0.11779   , 0.07476007],
        [0.52074348, 0.43356561, 0.12570985]],

       [[0.21016398, 0.44651403, 0.28806613],
        [0.22566409, 0.68643452, 0.56853983],
        [0.76041525, 0.97525929, 0.84451471],
        [0.13421399, 0.18822884, 0.56985184],
        [0.74735318, 0.45874263, 0.1615135 ]],

       [[0.92819205, 0.57415579, 0.86874637],
        [0.61420754, 0.78423346, 0.23895113],
        [0.04421963, 0.51115591, 0.04593596],
        [0.40806589, 0.03659577, 0.7399612 ],
        [0.61952791, 0.1610162 , 0.19144724]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [54]:
zero_matrix = np.zeros((10, 1))
false_matrix = zero_matrix.astype(np.bool).reshape((2, 5))
false_matrix

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [67]:
x =np.random.randint(10, 20, size = (5,2,6))

#1
print(f'El array tiene {x.size} elementos')

#2
print(f'El array tiene {x.ndim} dimensiones')

#3
print(f'El array tiene {x.shape[0]} elementos en la primera dimension, {x.shape[1]} elementos en la segunda dimension y {x.shape[2]} elementos en la tercera dimension'
)

El array tiene 60 elementos
El array tiene 3 dimensiones
El array tiene 5 elementos en la primera dimension, 2 elementos en la segunda dimension y 6 elementos en la tercera dimension


### Enlace a github : https://github.com/JoseKuru/bootcamp/blob/main/week4_EDA_np_pd_json_apis_regex/day1_numpy_pandas_I/exercises/EjerciciosNumpyI.ipynb