# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(10)
print(my_array[-1:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [5]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [15]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [60]:
matrix = np.arange(1, 21).reshape(4, 5)
print(matrix, matrix.T, sep='\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [23]:
print(matrix[0:2, 0:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [25]:
print(matrix[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [26]:
print(matrix[:-1, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [46]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [47]:
true_x = x == 'Loro'
print(x[true_x])

['Loro' 'Loro']


In [56]:
solo_loros = np.where(x=='Loro', 1, 0)
loro_indice = np.nonzero(solo_loros)
print(x[loro_indice])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [59]:
secuencia = [x for x in range(20)]
secuencia = np.array(secuencia).reshape(2, 5, 2)
secuencia

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [61]:
print(matrix[::-1, ::-1])

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [67]:
zero_array = np.zeros(10)
print(f'El array ocupa {zero_array.nbytes} bytes')
zero_array[3] = 1
print(zero_array)

El array ocupa 80 bytes
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [68]:
vector = np.arange(10, 50)
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [71]:
vector = np.array([1, 2, 0, 0, 4, 0])
indices = list(np.nonzero(vector)[0])
indices

[0, 1, 4]

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [81]:
aleatorio = np.random.rand(10, 10)
print(aleatorio)
print(f'El valor maximo es {aleatorio.max()} y el valor minimo {aleatorio.min()}')

[[0.30563097 0.93229606 0.48086701 0.72673924 0.87649583 0.9787531
  0.73389931 0.79208834 0.12887159 0.98248716]
 [0.33836726 0.26882912 0.40743139 0.14747331 0.3708369  0.53166894
  0.15447698 0.74516821 0.11086768 0.42183821]
 [0.68804037 0.70647795 0.68470773 0.49128318 0.52643949 0.68334061
  0.6145693  0.20693315 0.72229342 0.31513496]
 [0.09451541 0.88532816 0.45621159 0.50151089 0.72720053 0.09038663
  0.02062376 0.28050827 0.15825668 0.70562364]
 [0.32662748 0.56406602 0.52447997 0.06561112 0.4242877  0.80575674
  0.22639542 0.49266494 0.58289058 0.05630259]
 [0.1556693  0.8116516  0.33833887 0.73514449 0.32203768 0.48562381
  0.11702216 0.16825869 0.81710634 0.1720097 ]
 [0.37362479 0.42289367 0.73377796 0.09773999 0.60892554 0.26317527
  0.91805556 0.37332449 0.4849798  0.38488273]
 [0.80593178 0.88532662 0.1646823  0.25056363 0.76446139 0.7712044
  0.94781708 0.06780356 0.20601044 0.46356818]
 [0.61335925 0.17618303 0.42891751 0.05398423 0.39779735 0.84759017
  0.36572194 0

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [124]:
aleatorio = np.random.rand(30)
aleatorio.mean()

0.4969334333704933

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [198]:
array = np.zeros(shape=(6, 6), dtype='uint8')
array = np.pad(array, pad_width=1, constant_values=1)
print(array)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [203]:
matrix = np.ones(shape=(8, 8), dtype='uint8')
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if (i+j) % 2 == 0:
            matrix[i][j] = 0
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [210]:
matrix = np.array([[0, 1],[1,0]])
matrix = np.tile(matrix, (4, 4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [216]:
aleatoria = np.random.rand(5, 5)
aleatoria = (aleatoria - aleatoria.mean()) / aleatoria.std()
print(aleatoria)

[[-0.81422321 -1.0354973   0.20115281  0.39768433  1.17587392]
 [ 0.43297485  1.48085285  0.67761193 -1.63256282 -0.93402409]
 [-0.335216   -1.89791911  0.27866081  1.22936501  0.36079091]
 [-0.92469013 -0.24067218 -0.91414662  0.8994917  -0.98254687]
 [ 1.24123592  1.21506147 -1.03837375  1.46907827 -0.30996271]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [231]:
# 1
secuencia = np.arange(11)
# 2
secuencia2 = np.where((secuencia<8) & (secuencia>3), -1, secuencia)
# 3
secuencia3 = secuencia[np.where((secuencia>8) | (secuencia<3))]
print(secuencia, secuencia2, secuencia3, sep='\n')

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  9 10]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [56]:
import random

tablero = np.ndarray((10, 10), dtype='U1')       # Inicializo una array 10x10 con tipo de dato unicode de 1 byte
tablero[:] = ' '                                 # Asigno el valor (' ') a todo el array
tablero[0:2, 1] = 'O'                            # Asigno el barco de 2 de eslora
tablero[1, 3:7] = 'O'                            # Asigno el barco de 4 de eslora
tablero[1, 4] = 'X'                              # Un barco recibe un disparo 
tablero[6, 7] = '_'                              # Un disparo falla

diccionario_orientaciones = {'Norte' :0, 'Sur' :1, 'Este': 2, 'Oeste':3}
while True:

    x_inicial, y_inicial = random.randint(0, 9), random.randint(0, 9)
    orientacion = random.choice(list(diccionario_orientaciones.keys())) # Aqui elegimos unas coordenadas y oreintacion aleaotrias
    
    if diccionario_orientaciones[orientacion] == 0: # Norte
        if (y_inicial - 4 < 0) or not all(tablero[y_inicial -3 : y_inicial + 1, x_inicial] == ' '):
        # La primer condicion es verdad si el indice se va fuera del rango de la matriz
        # La segunda es verdad si hay algun barco o casilla ya marcada en el rango donde ira el barco
        # Si alguna es verdad el bucle se reiniciara y se utilizaran otras coordenadas
            continue
        for i in range(y_inicial, y_inicial - 4, -1):
            tablero[i][x_inicial] = 'O'

    elif diccionario_orientaciones[orientacion] == 1: # Sur
        if (y_inicial + 4 > 10) or not all(tablero[y_inicial: y_inicial + 4, x_inicial] == ' '):
            continue
        for i in range(y_inicial, y_inicial + 4):
            tablero[i][x_inicial] = 'O'

    elif diccionario_orientaciones[orientacion] == 2: # Este
        if (x_inicial + 4 > 10) or not all(tablero[y_inicial, x_inicial: x_inicial + 4] == ' '):
            continue
        for i in range(x_inicial, x_inicial + 4):
            tablero[y_inicial][i] = 'O'
            
    elif diccionario_orientaciones[orientacion] == 3: # Oeste
        if (x_inicial - 4 < 0) or not all(tablero[y_inicial, x_inicial -3 :x_inicial + 1] == ' '):
            continue
        for i in range(x_inicial, x_inicial - 4, -1):
            tablero[y_inicial][i] = 'O'
            
    break

print(f'Añadido barco de eslora 4 en la posicion inicial {(y_inicial, x_inicial)} con orientacion {orientacion}')
print(tablero)

Añadido barco de eslora 4 en la posicion inicial (9, 1) con orientacion Este
[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '_' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ' ' ' ' ']]
